# Source: jxboot-helmfile-resources/templates/repositories.yaml
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  name: "respository-jx"
  labels:
    jenkins.io/gitSync: "false"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
spec:
  description: "the git repository for the Respository-Jx environment"
  provider: "https://github.com"
  providerKind: 'github'
  providerName: 'github'
  org: "rgarciajim1980"
  repo: "respository_jx"
  httpCloneURL: "https://github.com/rgarciajim1980/respository_jx.git"
  url: "https://github.com/rgarciajim1980/respository_jx.git"
  scheduler:
    kind: Scheduler
    name: "in-repo"
